# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PC Engines
email: 

#write html inside the double quotes to display in jumbotron
description: "<h1>PC ENGINESâ„¢</h1><h3>Blog</h3>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pcengines.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown